# Generated by Django 6.0.1 on 2026-02-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'bike',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
