# Generated by Django 6.0.1 on 2026-02-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
