# Generated by Django 6.0.1 on 2026-02-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
        migrations.AlterModelTable(
            name='option',
            table='option',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
        migrations.AlterModelTable(
            name='response',
            table='response',
        ),
        migrations.AlterModelTable(
            name='survey',
            table='survey',
        ),
        migrations.AlterModelTable(
            name='surveytemplate',
            table='surveyTemplate',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
