# Generated by Django 6.0.1 on 2026-02-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productStock',
            field=models.PositiveIntegerField(),
        ),
    ]
