# Generated by Django 6.0.1 on 2026-02-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_productstatus_alter_product_productstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseType', models.CharField(max_length=100)),
                ('coursePrice', models.IntegerField()),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
