# Generated by Django 6.0.1 on 2026-02-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='courseStatus',
            field=models.BooleanField(null=True),
        ),
    ]
