# Generated by Django 6.0.1 on 2026-02-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_service_categoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerEmail', models.EmailField(max_length=254, unique=True)),
                ('customerPhone', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
