# Generated by Django 6.0.1 on 2026-02-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=50)),
                ('accountType', models.CharField(choices=[('Current', 'Current'), ('Savings', 'Savings')], max_length=50)),
                ('accountBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accountStatus', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.customer')),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=16, unique=True)),
                ('cardType', models.CharField(choices=[('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card')], max_length=25)),
                ('cardExpiryDate', models.DateField()),
                ('cardStatus', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.account')),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='customerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('customerDOB', models.DateField()),
                ('customerAddress', models.TextField()),
                ('customerCity', models.CharField(max_length=25)),
                ('customerState', models.CharField(max_length=25)),
                ('customerPincode', models.CharField(max_length=6)),
                ('customerId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.customer')),
            ],
            options={
                'db_table': 'customerProfile',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanType', models.CharField(choices=[('Home Loan', 'Home Loan'), ('Education Loan', 'Education Loan'), ('Personal Loan', 'Personal Loan')], max_length=25)),
                ('loanAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loanIntrestRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loanStatus', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.customer')),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Transfer', 'Transfer')], max_length=50)),
                ('transactionAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactionDate', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.account')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
