# Generated by Django 6.0.1 on 2026-02-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_account_card_customerprofile_loan_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerEmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerPhone',
            field=models.CharField(max_length=10),
        ),
    ]
